---
deployment:
  tasks:
    - export DEPLOYPATH=/home/reddevil/gbps.reddevils.co.in/
    - /bin/cp -r dist/* $DEPLOYPATH/
    - /bin/cp backend/api.php $DEPLOYPATH/api/index.php
    - /bin/cp backend/htaccess-api.txt $DEPLOYPATH/api/.htaccess
    - /bin/cp deploy/htaccess-spa.txt $DEPLOYPATH/.htaccess
    - /bin/mkdir -p $DEPLOYPATH/uploads
    - /bin/chmod 755 $DEPLOYPATH/uploads
